import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/component/header";
import Footer from "@/component/footer";
import { NextIntlClientProvider } from "next-intl";
import { cookies } from "next/headers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Rasses Location",
  description: "Generated by create next app",
};

async function fetchMessages(locale) {
  const BUCKET_BASE_URL = process.env.FIREBASE_MESSAGES_URL;
  const url = `${BUCKET_BASE_URL}${locale}.json?alt=media`;

  const res = await fetch(url, {
    next: { revalidate: 3600 },
  });

  if (!res.ok) {
    throw new Error(`Failed to fetch messages for locale "${locale}": ${res.status}`);
  }

  return res.json();
}

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const locale = cookieStore.get("site_lang")?.value || "en";
  const messages = await fetchMessages(locale);

  return (
    <html className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Header />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}